name: Build a zip
on:
  - push

jobs:
  build-run:
    # if: github.event_name == 'push' && contains(toJson(github.event.commits), '[run build pr]') != false
    runs-on: ubuntu-latest
    name: "Run npm build commands"
    steps:
      - name: Setup PHP without xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none

      - name: Install wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar --info
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: "Checkout"
        uses: actions/checkout@master

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Extract current branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # path: ~/.npm
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies and build
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

      - name: Run build
        run: npm run build

      - name: Build a package
        run: npm run build-zip

      - name: Upload zip  artifact
        uses: actions/upload-artifact@v2
        id: uag-zip-upload
        with:
          name: uag-zip
          path: ./ultimate-addons-for-gutenberg.zip

      - name: Download zip artifact
        uses: actions/download-artifact@v2
        id: uag-zip-download
        with:
          name: uag-zip
          path: ./temp/ultimate-addons-for-gutenberg.zip

      # - name: "Echo download path"
      #   run: echo ${{steps.uag-zip-download.outputs.download-path}}

      - name: QA site sync - rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --delete-excluded --exclude-from=".distignore" --include="" --filter=""
          # switches: -avzr --delete
          # path: ./temp/
          # remote_path: ${{ secrets.SSH_PATH }}
          remote_path: /home/runcloud/webapps/uag-dev/wp-content/uploads/uag-gh/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      # - name: "Echo download"
      #   run: echo print_r( ${{steps.uag-zip-download.outputs}} )
